- hosts: terraform-ansible
  tasks:
    - name: Install Python3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: Instalando django e djangorestframework no virtualenv
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando projeto Django dentro do virtualenv
      shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc'
    - name: Alterando host do settings.py para aceitar todas as requisições
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: '^ALLOWED_HOSTS =.*'
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes