- hosts: terraform-ansible
  tasks:
    - name: Install Python3 and virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: yes
    - name: Git Clone
      ansible.builtin.git:
        repo: 'https://github.com/guilhermeonrails/clientes-leo-api.git'
        dest: /home/ubuntu/tcc
        version: master
    - name: Instalando django e djangorestframework no virtualenv
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Alterando host do settings.py para aceitar todas as requisições
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: '^ALLOWED_HOSTS =.*'
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes